export const UserData = [
  {
    id: 1,
    username: "John",
    password: "123",
    email: null,
    isLogin: false,
    profilePictureUrl: "1715522467043-profile1.jpg",
    createTime: "2024-05-11 18:34:13",
    name: "John Doe",
    location: "Florida",
    gender: "Male",
    age: 20,
    interests: "Hockey, Fishing, Yoyo",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    school: "Florida State University",
    coverPicture: "1715522467045-cover1.jpg",
    createdAt: "2024-05-11 18:34:13",
    updatedAt: "2024-05-12 13:58:32",
  },
  {
    id: 2,
    username: "test",
    password: "123",
    email: null,
    isLogin: false,
    profilePictureUrl: "1715522939224-profile2.jpg",
    createTime: "2024-05-11 18:34:13",
    name: "Lulu",
    location: "Ohio",
    gender: "Female",
    age: 24,
    interests: "Dancing",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    school: "Ohio State University",
    coverPicture: "1715522939225-cover2.png",
    createdAt: "2024-05-11 18:34:13",
    updatedAt: "2024-05-12 14:07:53",
  },
  {
    id: 3,
    username: "yay",
    password: "123",
    email: null,
    isLogin: false,
    profilePictureUrl: "1715523512056-profile4.jpg",
    createTime: "2024-05-11 18:34:13",
    name: "Lori Jacobs",
    location: "NYC",
    gender: "Female",
    age: 24,
    interests: "Mario Kart",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    school: "Hunter College",
    coverPicture: "1715523512058-cover.jpg",
    createdAt: "2024-05-11 18:34:13",
    updatedAt: "2024-05-11 20:05:45",
  },
  {
    id: 4,
    username: "rabbit",
    password: "123",
    email: null,
    isLogin: false,
    profilePictureUrl: "1715523115881-profile3.jpg",
    createTime: "2024-05-11 18:34:13",
    name: "Jimmy Smith",
    location: "California",
    gender: "Male",
    age: 19,
    interests: "Fishing, Chess",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    school: "Berkeley",
    coverPicture: "1715523115882-profile4.jpg",
    createdAt: "2024-05-11 18:34:13",
    updatedAt: "2024-05-12 14:10:48",
  },
];

export const PostData = [
  {
    postId: 1,
    userId: 3,
    content: "A new post",
    imageUrl: "1715458008569-comic-cat.jpg",
    createdAt: null,
    updatedAt: null,
  },
  {
    postId: 2,
    userId: 3,
    content: "testing another post",
    imageUrl: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    postId: 3,
    userId: 3,
    content: "The picture",
    imageUrl: "1715467745303-default.jpg",
    createdAt: null,
    updatedAt: null,
  },
  {
    postId: 4,
    userId: 3,
    content: "Another picture",
    imageUrl: "1715475707707-comic-dog.jpg",
    createdAt: null,
    updatedAt: null,
  },
  {
    postId: 5,
    userId: 1,
    content:
      "Hi, my name is John Doe! I like sports. Here is a picture of Kobe Bryant, my favorite basketball player.",
    imageUrl: "1715522566622-Kobe_Bryant_2014.jpg",
    createdAt: null,
    updatedAt: null,
  },
  {
    postId: 6,
    userId: 2,
    content:
      "My name is Lulu. I like dancing. Here is a picture of jojo siwa. My favorite dancer",
    imageUrl: "1715523019146-jojo.jpg",
    createdAt: null,
    updatedAt: null,
  },
  {
    postId: 7,
    userId: 4,
    content: "I love fishing!!",
    imageUrl: "1715523171793-fishing.jpg",
    createdAt: null,
    updatedAt: null,
  },
];

export const CommentData = [
  {
    commentId: 1,
    postId: 1,
    userId: 3,
    content: "a comment",
    createTime: null,
  },
  {
    commentId: 2,
    postId: 1,
    userId: 3,
    content: "another comment",
    createTime: null,
  },
  {
    commentId: 3,
    postId: 5,
    userId: 1,
    content: "testing comments",
    createTime: null,
  },
];

export const FriendData = [
  {
    friendshipId: 1,
    followedUser: 1,
    followingUser: 3,
    status: "active",
  },
  {
    friendshipId: 2,
    followedUser: 2,
    followingUser: 1,
    status: "active",
  },
  {
    friendshipId: 3,
    followedUser: 3,
    followingUser: 4,
    status: "active",
  },
  {
    friendshipId: 4,
    followedUser: 2,
    followingUser: 4,
    status: "active",
  },
];

export const LikeData = [
  {
    likeId: 2,
    postId: 1,
    userId: 3,
    createTime: null,
  },
  {
    likeId: 3,
    postId: 4,
    userId: 3,
    createTime: null,
  },
  {
    likeId: 4,
    postId: 2,
    userId: 3,
    createTime: null,
  },
  {
    likeId: 5,
    postId: 4,
    userId: 1,
    createTime: null,
  },
  {
    likeId: 6,
    postId: 5,
    userId: 4,
    createTime: null,
  },
  {
    likeId: 7,
    postId: 2,
    userId: 4,
    createTime: null,
  },
];

export const StatData = [
  {
    userId: 1,
    postCount: 1,
    commentCount: 1,
    likeCount: 1,
    friendCount: 1,
    shareCount: 0,
    createdAt: null,
    updatedAt: null,
  },
  {
    userId: 2,
    postCount: 1,
    commentCount: 0,
    likeCount: 0,
    friendCount: 0,
    shareCount: 0,
    createdAt: null,
    updatedAt: null,
  },
  {
    userId: 3,
    postCount: 3,
    commentCount: 1,
    likeCount: 4,
    friendCount: 1,
    shareCount: 0,
    createdAt: null,
    updatedAt: null,
  },
  {
    userId: 4,
    postCount: 1,
    commentCount: 0,
    likeCount: 2,
    friendCount: 2,
    shareCount: 0,
    createdAt: null,
    updatedAt: null,
  },
];
